[package]
name = "qr-text"
version = "0.1.0"
authors = ["Yoshihito Hirakawa <hirakawa.yoshihito@classmethod.jp>"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.23"
qrcode = "0.12"
thiserror= "1.0"
